### ISSUE TITLE
About 2d bbox regression

### ISSUE THREAD

**Issue by JagrZlhan** [benchun123/point-plane-object-SLAM#2]
hello benchun,
I think your work has a wonderful performance, but when reading your article, I have a question about the 2d bbox regression step, i.e. how can we get an object's 2D bbox on the ground plane from a rgb image? 
hope for your reply:) thanks

**Comment by benchun123** [comment]
Hi JagrZlhan, 

Thanks for your interests, actually I do not totally understand your question. 

To get objects' 2D bounding box in image, we use [yolo](https://github.com/ultralytics/yolov5)
To get the ground plane, we use multiple plane estimation in [PCL library](https://jsk-docs.readthedocs.io/projects/jsk_recognition/en/latest/jsk_pcl_ros/nodes/organized_multi_plane_segmentation.html), for more plane estimation from an RGB or RGB-D image, you can find a [survey](https://github.com/benchun123/PhD/blob/main/Paper%20Survey%20on%20Plane%20SLAM.md)

Best regards,

**Comment by JagrZlhan** [comment]
understand. I misunderstood the meaning of  "2d bbox regression" and thought we must get a 2d bbox on ground at first. 
Actually, we just need to sample dimensions and yaw to get many 3d bbox candidates.
Thanks for your answer!
