### ISSUE TITLE
The 400 images chosen for SUN-RGBD dataset?

### ISSUE THREAD

**Issue by Mechazo11** [benchun123/point-plane-object-SLAM#3]
Hello @benchun123 

Thank you very much for making your code open source and the paper publicly available. I am trying to compare your method against a cuboid detection strategy that I am currently working on.

In section 4.1.2, the paper states the following "To compare our proposed detection method with SUN Primitive [35] and CubeSLAM [20], we select **400 images with visible ground planes and fully visible ground objects**"

May I have a copy of those 400 images so that I can test the 3D IoU approach with Structure SLAM for appropriate comparison?

With best,
@Mechazo11

**Comment by benchun123** [comment]
Hello @Mechazo11 

Thanks for your question, I upload the small dataset on [google drive](https://drive.google.com/file/d/14PQWSmCsBvmomllWeF4_hlDiEuYIyWgQ/view?usp=sharing), together with my results and evaluation tools. If you have problem on download, please send me a place that I can upload. 

If you have any other problem, just let me know. 

Best regards, 
Benchun Zhou

**Comment by Mechazo11** [comment]
Hi @benchun123 sorry for the late reply. I shall test the link and let you know if I have any issues. For now closing this issue.
