### ISSUE TITLE
Confusion regarding Equations 1 and $P_{roj}$

### ISSUE THREAD

**Issue by Mechazo11** [benchun123/point-plane-object-SLAM#4]
Hello @benchun123 

In your paper, how is $X_{3D}$ computed? After Equation 1 it appears $X_{3D}$ points are no longer used. 

![image](https://github.com/benchun123/point-plane-object-SLAM/assets/44814419/3fe95a49-e750-47a5-9dd3-7ad31b0f30d5)

Are you using vanishing point methods similar to how CubeSLAM first find 8 corners in 2d plane and then use PnP to project them to 3D space to find the 3d position of the 8 corners of the cuboid?

Also is $P_{roj}$ equal to $K$ the calibration matrix?

**Comment by benchun123** [comment]
Hello @Mechazo11 , 

Thanks for following my work. Actually, we use another 2D-3D fitting constraints to lift 2D bounding box to 3D cuboid. As we show in the paper: the projected vertexes of a 3D cuboid should fit tightly into each side of its 2D detection box. That means, four out of eight vertexes of the 3D bounding box should be projected right on the four sides of the 2D bounding box.

In my experiments on SUN RGB-D dataset, the projection matrix is 3*4, where the block(0,0,3,3) is K. 

I currently make the [monocular object detection method](https://github.com/benchun123/monocular_object_detection)  open source, then you can clearly know how it works. 

Best regards,
Benchun Zhou

**Comment by Mechazo11** [comment]
@benchun123 thank you very much for making the cuboid method open source. This will greatly help me to understand the process.
